name: 'Run ThirdParties scan'
description: 'Run a third-party scripts scan on an URL'
inputs:
  url: 
    description: 'URL ro scan'
    required: true
  output:
    description: 'Path to output file. defaults to thirdparties.json'
    default: 'thirdparties.json'
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        cd ${{ github.action_path }}
        yarn
        node src/scan ${{ inputs.url }} > ${{ github.workspace }}/${{ inputs.output }}