name: "Run ThirdParties scan"
description: "Run a third-party scripts scan on an URL"
inputs:
  url:
    description: "URL ro scan"
    required: true
  output:
    description: "Path to output file. defaults to thirdparties.json"
    default: "thirdparties.json"
    required: true
outputs:
  trackers:
    description: "Third parties json as output string"
    value: ${{ fromJson(steps.thirdparties.outputs['json-output']).trackers }}

runs:
  using: "composite"
  steps:
    - id: thirdparties
      shell: bash
      run: |
        cd ${{ github.action_path }}
        yarn
        JSON_OUTPUT=$(node src/scan ${{ inputs.url }} | tee -a ${{ github.workspace }}/${{ inputs.output }})
        echo "::set-output name=json-output::$JSON_OUTPUT"
