name: "Run ThirdParties scan"
description: "Run a third-party scripts scan on an URL"
inputs:
  url:
    description: "URL ro scan"
    required: true
  output:
    description: "Path to output file. defaults to thirdparties.json"
    default: "thirdparties.json"
    required: true
outputs:
  third-parties-output:
    description: "Third parties json as output string"
    value: ${{ steps.thirdparties.json-ouput }}

runs:
  using: "composite"
  steps:
    - id: thirdparties
      shell: bash
      run: |
        cd ${{ github.action_path }}
        yarn
        echo "::set-output name=json-ouput::$(node src/scan ${{ inputs.url }} | tee -a ${{ github.workspace }}/${{ inputs.output }})"
