name: "Run ThirdParties scan"
description: "Run a third-party scripts scan on an URL"
inputs:
  url:
    description: "URL ro scan"
    required: true
  output:
    description: "Path to output file. defaults to thirdparties.json"
    default: "thirdparties.json"
    required: true
outputs:
  thirdpartiesJson:
    description: "Third parties json as output string"
    value: ${{ steps.thirdparties.outputs.jsonOutput }}

runs:
  using: "composite"
  steps:
    - id: thirdparties
      shell: bash
      run: |
        cd ${{ github.action_path }}
        yarn
        JSON_OUTPUT=$(node src/scan ${{ inputs.url }} | tee -a ${{ github.workspace }}/${{ inputs.output }})
        JSON_OUTPUT_FORMATTED=$(echo $JSON_OUTPUT | sed 's/ //g')
        echo "::set-output name=jsonOutput::$JSON_OUTPUT_FORMATTED"
